### ISSUE TITLE
Code cleanup and improvements

### ISSUE THREAD

**Issue by SpaceOgre** [NorthernLight1/N.EntityFrameworkCore.Extensions#68]
Not sure if you would like help with this but I saw some things that could be improved in the code and also structure it so it is easier to maintain and get into.

Creating this issue first before I do anything that you might not want any way.

Suggestions:
- [x] Add an .editorconfig file to enforce code standards in the solution
  - [x] Run `dotnet format` after this and submit a PR with all fixes this produces
- [ ] Since only Net 8 is targeted go over and use collection initializers where possible 
- [ ] Use char methods where possible, like in CommonUtil.cs since this has better performance
- [ ] Use StringBuilder where possible for better performance and less allocations
- [ ] Order methods by their access level, so like public, internal, protected, private
- [ ] internal classes can be sealed, small performance boost
- [ ] Group overload methods together
- [ ] Remove code that is commented out
- [ ] In LinqExtensions instead of dictionary sqlExpressionTypes, a switch expression will be faster
  - [ ] Look for similar improvements
- [ ] See if Spans can be used instead of other collections/strings

There is more but starts with this to see if you want help with this and if so how you would like to proceed since it might create lots of conflicts for some of the changes.

**Comment by NorthernLight1** [comment]
SpaceOrge,

These are all great suggestions, and I would definitely accept any help to improve this library so feel free to contribute whatever you like. I don't see any issue with all the points that you mentioned so far. I would ask that any pull requests you do go to the development branch. 

In regards to .editorconfig file, I am not very familiar it, since I have never used it before, but I think it is a great idea and I am going to look into it tonight. Do you have a basic starter file that I could review?

**Comment by SpaceOgre** [comment]
I have used the `.editorconfig` that the dotnet team uses as a starter before and are happy with that:
https://github.com/dotnet/runtime/blob/main/.editorconfig

**Comment by NorthernLight1** [comment]
I research it yesterday and I agree we should adopt it into this project. The file you suggested looks good. I would say lets start with that one and change it as needed.

**Comment by NorthernLight1** [comment]
I am closing this ticket, we can re-open if there is any progress.
